### ISSUE TITLE
V2 - TODO

### ISSUE THREAD

**Issue by enchant97** [enchant97/web-portal#22]
This will record tasks of what needs to be done for the next major version (V2) of web-portal.

# Tasks
- [x] Plugin Loader & API
    - [x] Compatibility checking (min/max version, conflict detection)
    - [X] Registering widgets and such
- [x] Documentation
    - [x] User (setup and use)
    - [x] Developer (plugin, etc)
- [x] Core Plugin Widgets (provided in base install)
    - [x] Link
        - [X] Add optional icons
        - [x] Make a icons uploader (upload a zip with icons in png and svg folder)
    - [x] Search Box (for internet searches)
    - [X] HTML Embed
    - [x] Digital Clock
    - [x] Iframe embed
    - ~Basic server stats (memory, cpu)~
- [x] More authentication decorators
- [x] Admins can force login as other users (non-admin)
- [X] Wizard for initial setup
- [x] Implement new unit tests
- [x] Improved app logging
- [x] Make guest a virtual account for public dashboards
    - [x] Only logged in via force-login (Only accessible when public dash is enabled)
    - [x] Remove from setup wizard
    - [x] Ensure guest account always exists
    - [x] Rename account to "public"
- [x] Rename UNSECURE_LOGIN to SECURE_COOKIES
- [x] Clean-up of removed registered plugins (does not remove anything made by a plugin)
- [x] (core plugin) Handle accessing multiple links with same id
- [x] Recover from plugins being removed
- [x] Buttons overlap slightly
- [x] Move widgets (html embed & iframe) into another plugin called "core_extras"
- [x] Custom CSS overriding, through admin interface
- [x] - Group widget load fails into one error (prevent massive screen of flashed errors) e.g. `widgets with names (name, name_2) could not be loaded, please contact administrator`
- [x] Tidy code, performance improving (if possible)
- [x] Internal testing

# V2.X
Features that will come after V2 release
- Split plugins into git submodules. Make a plugin organisation, for community additions
- Allow each placed widget to customise whether the header is shown
- Don't rely on Pydantic for config loading
- Allow admins to disallow non admin users from creating personal dashboards
- A API for plugins to implement, to enable plugins to interact with other plugins
- External auth support
- Notification System
- Better Plugin Uninstall
    - Plugins clean-up themselves before removal (if authors implement it properly)
- Drag N Drop ability in widgets customisation
